In [19]:
import sys
sys.path.append("./src")

In [20]:
from extract import extract_products, url, limit
products = extract_products(url, limit)

API acessada com sucesso!

In [21]:
len(products)

20

In [22]:
import pandas as pd

df = pd.DataFrame(products)
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [23]:
df.columns

Index(['id', 'title', 'description', 'category', 'price', 'discountPercentage',
       'rating', 'stock', 'tags', 'brand', 'sku', 'weight', 'dimensions',
       'warrantyInformation', 'shippingInformation', 'availabilityStatus',
       'reviews', 'returnPolicy', 'minimumOrderQuantity', 'meta', 'images',
       'thumbnail'],
      dtype='object')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    20 non-null     int64
 1   title                 20 non-null     object
 2   description           20 non-null     object
 3   category              20 non-null     object
 4   price                 20 non-null     float64
 5   discountPercentage    20 non-null     float64
 6   rating                20 non-null     float64
 7   stock                 20 non-null     int64
 8   tags                  20 non-null     object
 9   brand                 15 non-null     object
 10  sku                   20 non-null     object
 11  weight                20 non-null     int64
 12  dimensions            20 non-null     object
 13  warrantyInformation   20 non-null     object
 14  shippingInformation   20 non-null     object
 15  availabilityStatus    20 non-null     object
 16  reviews               20 non-null     object
 17  returnPolicy          20 non-null     object
 18  minimumOrderQuantity  20 non-null     int64
 19  meta                  20 non-null     object
 20  images                20 non-null     object
 21  thumbnail             20 non-null     object
dtypes: float64(3), int64(4), object(15)
memory usage: 3.6+ KB

In [25]:
df.describe()

,id,price,discountPercentage,rating,stock,weight,minimumOrderQuantity
count,20.00000,20.00000,20.000000,20.000000,20.000000,20.00000,20.000000
mean,10.50000,326.29000,10.897500,3.884000,58.200000,6.70000,16.200000
std,5.91608,678.64882,5.059089,0.750722,34.801089,3.02794,16.343677
min,1.00000,1.99000,0.620000,2.560000,4.000000,1.00000,1.000000
25%,5.75000,9.99000,9.197500,3.175000,28.250000,4.75000,2.000000
50%,10.50000,34.99000,10.960000,4.075000,62.000000,7.00000,9.500000
75%,15.25000,172.49000,14.392500,4.395000,89.500000,9.25000,22.000000
max,20.00000,2499.99000,19.090000,4.880000,99.000000,10.00000,48.000000

In [26]:
df = df[['id', 'title', 'category', 'price', 'discountPercentage', 'rating']]
df.head()

,id,title,category,price,discountPercentage,rating
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86
2,3,Powder Canister,beauty,14.99,9.84,4.64
3,4,Red Lipstick,beauty,12.99,12.16,4.36
4,5,Red Nail Polish,beauty,8.99,11.44,4.32

In [27]:
df.shape

(20, 6)

In [28]:
df.isna().sum()

id                    0
title                 0
category              0
price                 0
discountPercentage    0
rating                0
dtype: int64

In [29]:
df.dtypes

id                      int64
title                  object
category               object
price                 float64
discountPercentage    float64
rating                float64
dtype: object

In [30]:
import os
os.getenv("OPENAI_API_KEY")[:7]

'sk-proj'

In [31]:
from openai import OpenAI

client = OpenAI()

def generate_ai_news(product):
    
    try:
        prompt = f'''
    Você é um especialista em marketing de e-commerce.
    Crie uma frase curta em português, com no máximo 120 caracteres,
    sobre este produto, sem inventar informações.

    Produto: {product['title']}
    Categoria: {product['category']}
    Preço: {product['price']}
    Desconto: {product['discountPercentage']}%
    Avaliação: {product['rating']}/5
    '''.strip()

        response = client.responses.create(
            model='gpt-4o-mini',
            input=prompt
        )
        
        return response.output_text.strip()
        
    except Exception:
        print('Falha ao usar o OpenAI')

In [32]:
sample = df.iloc[0].to_dict()
generate_ai_news(sample)

Falha ao usar o OpenAI

In [33]:
products_transformed = df.to_csv('../data/processed/products_transformed.csv', index=False)
products_transformed

OSError: Cannot save file into a non-existent directory: '../data/processed'

In [ ]:
import pandas as pd

pd.read_csv('../data/processed/products_transformed.csv').head()

,id,title,category,price,discountPercentage,rating
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86
2,3,Powder Canister,beauty,14.99,9.84,4.64
3,4,Red Lipstick,beauty,12.99,12.16,4.36
4,5,Red Nail Polish,beauty,8.99,11.44,4.32